service: aws-node-express-api-esm-iitm
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-2
  tracing:
    lambda: true
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/nodejs-otel-handler
    OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,service.version=1.0
    OTEL_SERVICE_NAME: aws-node-express-api-dev-api-esm-iitm
    SPLUNK_ACCESS_TOKEN: n79JFIhE1X22WUM61yUn5Q
    SPLUNK_REALM: us0
    OPENTELEMETRY_EXTENSION_LOG_LEVEL: debug
    OTEL_LAMBDA_LOG_LEVEL: debug

layers:
  customotel:
    path: custom-js-layer
    name: ${sls:stage}-custom-js-layer
    compatibleRuntimes:
      - nodejs16.x
    compatibleArchitectures:
      - x86_64
functions:
  api:
    handler: services/main.handler
    events:
      - httpApi: "*"
    layers:
      - !Ref CustomotelLambdaLayer
      - arn:aws:lambda:ap-southeast-2:254067382080:layer:splunk-apm-collector:6
